### ISSUE TITLE
Completed module 2 assignments

### ISSUE THREAD

**Issue by NGRB256** [ds4owd-001/md-02-assignments-NGRB256#1]
@larnsce @mianzg @sskorik01

**Comment by sskorik01** [comment]
Hi, you haven't committed your code (your code in md-02a-data-visualization.qmd has not been updated on GitHub). You have to commit and push from Posit.cloud to confirm you have finished your assignment.

**Comment by NGRB256** [comment]
I've made changes, please let me know if you can see them.

**Comment by larnsce** [comment]
Thank you, @NGRB256. Your changes are still not reflected on GitHub. Did you try to push? And did it ask your for your GitHub username and password (you would need to enter your GitHub PAT here)?

Can you share a screenshot of your assignment 2 in RStudio showing the Git pane in the top-right window. Below an example screenshot:

![Screenshot 2023-11-15 at 09 49 38](https://github.com/ds4owd-001/md-02-assignments-NGRB256/assets/18212549/560d4149-9fbb-4cdc-b3e9-745b097a055a)

**Comment by sskorik01** [comment]
Hey, did you try to push again? Because the code has not been updated yet. Are you maybe getting an error message when trying?
